openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: pong