openapi: 3.0.0
info:
  title: Products API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Search products
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Query'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                MultipleProducts:
                  value:
                    - name: "Product A"
                      expiration_datetime: "2024-12-31T23:59:59Z"
                      price: 19.99
                    - name: "Product B"
                      expiration_datetime: "2024-06-30T12:00:00Z"
                      price: 29.99
                EmptyList:
                  value: []
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
    Query:
      name: q
      in: query
      required: false
      schema:
        type: string